\@setckpt{RF/RF}{
\@setckpt{conclusion/conclusion}{
\@setckpt{elecbox/elecbox}{
\@setckpt{intro/intro}{
\@setckpt{mechanics/mechanics}{
\@writefile{lof}{\contentsline {figure}{\numberline {1}{\ignorespaces Left:Nono, Right: Eva}}{3}{figure.1}}
\@writefile{lof}{\contentsline {figure}{\numberline {2}{\ignorespaces Left: helix antenna, circled the hole where water went into the LNA box. Right: rust in Santy's LNA box}}{4}{figure.2}}
\@writefile{lof}{\contentsline {figure}{\numberline {3}{\ignorespaces antenna VSWR, measured in lab}}{5}{figure.3}}
\@writefile{lof}{\contentsline {figure}{\numberline {4}{\ignorespaces LNA VSWR}}{5}{figure.4}}
\@writefile{lof}{\contentsline {figure}{\numberline {5}{\ignorespaces LNA gain. The measurement of the gain was done with a 50dB attenuator.}}{6}{figure.5}}
\@writefile{lof}{\contentsline {figure}{\numberline {6}{\ignorespaces setup to evaluate the electronics box characteristics. The LNA and the load are installed in a LNA box with an antenna over it, but the antenna is NOT connected.}}{7}{figure.6}}
\@writefile{lof}{\contentsline {figure}{\numberline {7}{\ignorespaces example of trace of the box 4 (left) and zoomed (right)}}{8}{figure.7}}
\@writefile{lof}{\contentsline {figure}{\numberline {8}{\ignorespaces baseline versus time for the box number 9}}{8}{figure.8}}
\@writefile{lof}{\select@language{english}}
\@writefile{lot}{\contentsline {table}{\numberline {1}{\ignorespaces correspondence table between detector numbers}}{2}{table.1}}
\@writefile{lot}{\contentsline {table}{\numberline {2}{\ignorespaces average and RMS measurement of the electronics boxes}}{7}{table.2}}
\@writefile{lot}{\select@language{english}}
\@writefile{toc}{\contentsline {paragraph}{remarks}{7}{section*.1}}
\@writefile{toc}{\contentsline {section}{\numberline {1}Introduction}{2}{section.1}}
\@writefile{toc}{\contentsline {section}{\numberline {2}Mechanics}{3}{section.2}}
\@writefile{toc}{\contentsline {section}{\numberline {3}Antenna and LNA}{5}{section.3}}
\@writefile{toc}{\contentsline {section}{\numberline {4}electronic box}{7}{section.4}}
\@writefile{toc}{\contentsline {section}{\numberline {5}conclusions}{9}{section.5}}
\@writefile{toc}{\select@language{english}}
\AC@reset@newl@bel
\AtEndDocument{\ifx\hyper@anchor\@undefined
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\bibdata{easier}
\bibstyle{atlasnote}
\fi}
\fi}
\gdef\HyperFirstAtBeginDocument#1{#1}
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\global\let\hyper@last\relax 
\global\let\oldcontentsline\contentsline
\global\let\oldnewlabel\newlabel
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\newlabel{fig:box9vstime}
\newlabel{fig:cone}
\newlabel{fig:lnabox}
\newlabel{fig:lnas11}
\newlabel{fig:lnas21}
\newlabel{fig:peaks}
\newlabel{fig:setupbox}
\newlabel{fig:vswrant}
\newlabel{tab:boxtab}
\newlabel{tab:detref}
\providecommand\HyField@AuxAddToCoFields[2]{}
\providecommand\HyField@AuxAddToFields[1]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\providecommand\hyper@newdestlabel[2]{}
\select@language{english}
\setcounter{@todonotes@numberoftodonotes}{0}
\setcounter{@todonotes@numberoftodonotes}{0}
\setcounter{@todonotes@numberoftodonotes}{0}
\setcounter{@todonotes@numberoftodonotes}{0}
\setcounter{@todonotes@numberoftodonotes}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{4}
\setcounter{Item}{4}
\setcounter{LN@truepage}{2}
\setcounter{LN@truepage}{4}
\setcounter{LN@truepage}{6}
\setcounter{LN@truepage}{8}
\setcounter{LN@truepage}{9}
\setcounter{bookmark@seq@number}{1}
\setcounter{bookmark@seq@number}{2}
\setcounter{bookmark@seq@number}{3}
\setcounter{bookmark@seq@number}{4}
\setcounter{bookmark@seq@number}{5}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{4}
\setcounter{enumi}{4}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{figure}{0}
\setcounter{figure}{2}
\setcounter{figure}{5}
\setcounter{figure}{8}
\setcounter{figure}{8}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{linenumber}{14}
\setcounter{linenumber}{24}
\setcounter{linenumber}{42}
\setcounter{linenumber}{78}
\setcounter{linenumber}{89}
\setcounter{lofdepth}{1}
\setcounter{lofdepth}{1}
\setcounter{lofdepth}{1}
\setcounter{lofdepth}{1}
\setcounter{lofdepth}{1}
\setcounter{lotdepth}{1}
\setcounter{lotdepth}{1}
\setcounter{lotdepth}{1}
\setcounter{lotdepth}{1}
\setcounter{lotdepth}{1}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{page}{10}
\setcounter{page}{3}
\setcounter{page}{5}
\setcounter{page}{7}
\setcounter{page}{9}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{parentequation}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{1}
\setcounter{section@level}{4}
\setcounter{section}{1}
\setcounter{section}{2}
\setcounter{section}{3}
\setcounter{section}{4}
\setcounter{section}{5}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subfigure}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{subtable}{0}
\setcounter{table}{1}
\setcounter{table}{1}
\setcounter{table}{1}
\setcounter{table}{2}
\setcounter{table}{2}
}
}
}
}
}
