\newlabel{eq:eqdeltabsqrt}
\newlabel{eq:eqdeltab}
\newlabel{eq:sigmamu}
\newlabel{fig:bwfilt2}
\newlabel{fig:bwfilt}
\newlabel{fig:carac}
\newlabel{fig:datatrace}
\newlabel{fig:datatrace}
\newlabel{fig:datatrace}
\newlabel{fig:detscheme}
\newlabel{fig:exampleboard}
\newlabel{fig:examplefft}
\newlabel{fig:fitboard}
\newlabel{fig:flatspec}
\newlabel{fig:m1_distdata}
\newlabel{fig:m1ex}
\newlabel{fig:m2_distdata}
\newlabel{fig:m2ex}
\newlabel{fig:m3_distdata}
\newlabel{fig:m3ex}
\newlabel{fig:pdcarac}
\newlabel{fig:pdspec1}
\newlabel{fig:pdspec2}
\newlabel{fig:signalexample}
\newlabel{fig:simboard}
\newlabel{fig:slidingwindow}
\newlabel{fig:spectra}
\newlabel{fig:spectra}
\newlabel{sec:elec}
\newlabel{sec:rf}
\newlabel{sec:theory}
\newlabel{tab:easierdetectors}
\newlabel{tab:method1tab}
\newlabel{tab:tabdeltab}
