\newlabel{eq:tant}
\newlabel{eq:tsys}
\newlabel{fig:aeffuncert}
\newlabel{fig:blvstempraw}
\newlabel{fig:completesim}
\newlabel{fig:examplefit}
\newlabel{fig:f107}
\newlabel{fig:selectedpopey}
\newlabel{fig:spectra}
\newlabel{fig:sunflux}
\newlabel{fig:zenithofmax}
\newlabel{sec:tempdep}
